version: '3.8'

services:
  app:
    build: .
    container_name: gestion-viajes-app
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge