name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests
      
    - name: Run Tests
      run: ./mvnw test
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: application
        path: target/*.war 